apiVersion: v1
entries:
  harness-delegate-ng:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.087375012Z"
    description: A Helm chart for deploying harness-delegate
    digest: b91b57f374c0ceb73004949ab6507bc8ebad356a6381d10c947e1297e318744f
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.086531795Z"
    description: A Helm chart for deploying harness-delegate
    digest: fb1c0c7b29b210291ef7aa9a25ebf928001f735917156b46a1dfa8169e0ae7cf
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.085843816Z"
    description: A Helm chart for deploying harness-delegate
    digest: 7e4f4b8bde62bd465e5d331f37ab7500dde6e4f48e7b31e4826eb64f86e2fd33
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.085115622Z"
    description: A Helm chart for deploying harness-delegate
    digest: 52b7cce92e920cec2b0c4e60b0c647abbbe6f96801debeaf4599dd21b5222f57
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.084467052Z"
    description: A Helm chart for deploying harness-delegate
    digest: 8474985e68458c90ce77c014f90e1aa7973ef2db112cdb5e03131cb15d8f3ac2
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.083773789Z"
    description: A Helm chart for deploying harness-delegate
    digest: 8dfb8e28b527b0dc30a61b53abd600071f1c207504f36599c8cd986987227b59
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.083024201Z"
    description: A Helm chart for deploying harness-delegate
    digest: 2fcc420a2a9cc396a000c977c536f8e5d510b6208312fc88b7c2c0cd2fd159e9
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.082227158Z"
    description: A Helm chart for deploying harness-delegate
    digest: 1b0689296cc54878fef978c6b00dc5df934a4cd01e0d1619ca645d0b1406df9b
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-20T02:40:34.081392681Z"
    description: A Helm chart for Kubernetes
    digest: 93951364b96a84f1b4a8e2045ff21f2bb94cbe432693c971047b60ca9abed27a
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.0.tgz
    version: 1.0.0
generated: "2023-01-20T02:40:34.079082795Z"
