apiVersion: v1
entries:
  harness-delegate-ng:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.11042565Z"
    description: A Helm chart for deploying harness-delegate
    digest: f73d82083dd266063dc0e2f484c79fbc80d9cae0953d0025c7326c3c4e2bf220
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.16.tgz
    version: 1.0.16
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.109391294Z"
    description: A Helm chart for deploying harness-delegate
    digest: 2956aac00f09f06b1bfc267e1d5059f016ab2f9da9c7c23f74eacde0fa370c4a
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.15.tgz
    version: 1.0.15
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.108422621Z"
    description: A Helm chart for deploying harness-delegate
    digest: 08be64b59c9c716db9d4ef9225e70b488d6581887d9b8e0f81193c81a0b33aa4
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.14.tgz
    version: 1.0.14
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.107477715Z"
    description: A Helm chart for deploying harness-delegate
    digest: 22c2e730113ad38f21aaddd2ebf1b2851bbeb022bd78718adc3aaf73f892e862
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.13.tgz
    version: 1.0.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.106519364Z"
    description: A Helm chart for deploying harness-delegate
    digest: 36cf9e271086884e6b8bf683528a72a18fad05852d5774f745fd8e6833b9b43a
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.12.tgz
    version: 1.0.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.105594198Z"
    description: A Helm chart for deploying harness-delegate
    digest: ee5740e1dd7652b33deffde193fa5f48dbb1bc345efaef66001fc8752ca6dbba
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.11.tgz
    version: 1.0.11
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.104646765Z"
    description: A Helm chart for deploying harness-delegate
    digest: 9fc3f3b113541143d6d0e860d6c120f2dae077c6ac05423abb9da801255f384c
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.10.tgz
    version: 1.0.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.116689698Z"
    description: A Helm chart for deploying harness-delegate
    digest: b6ea67add03357b6fa73f22c6795cd1c0628b60b61ac50fc94fb93eb887005b7
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.11591318Z"
    description: A Helm chart for deploying harness-delegate
    digest: fb1c0c7b29b210291ef7aa9a25ebf928001f735917156b46a1dfa8169e0ae7cf
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.115171505Z"
    description: A Helm chart for deploying harness-delegate
    digest: 7e4f4b8bde62bd465e5d331f37ab7500dde6e4f48e7b31e4826eb64f86e2fd33
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.114459367Z"
    description: A Helm chart for deploying harness-delegate
    digest: 52b7cce92e920cec2b0c4e60b0c647abbbe6f96801debeaf4599dd21b5222f57
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.113653889Z"
    description: A Helm chart for deploying harness-delegate
    digest: 8474985e68458c90ce77c014f90e1aa7973ef2db112cdb5e03131cb15d8f3ac2
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.112887888Z"
    description: A Helm chart for deploying harness-delegate
    digest: 8dfb8e28b527b0dc30a61b53abd600071f1c207504f36599c8cd986987227b59
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.112147827Z"
    description: A Helm chart for deploying harness-delegate
    digest: 2fcc420a2a9cc396a000c977c536f8e5d510b6208312fc88b7c2c0cd2fd159e9
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.111277463Z"
    description: A Helm chart for deploying harness-delegate
    digest: 1b0689296cc54878fef978c6b00dc5df934a4cd01e0d1619ca645d0b1406df9b
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-14T12:11:13.102089894Z"
    description: A Helm chart for Kubernetes
    digest: 93951364b96a84f1b4a8e2045ff21f2bb94cbe432693c971047b60ca9abed27a
    name: harness-delegate-ng
    type: application
    urls:
    - harness-delegate-ng-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-14T12:11:13.100918115Z"
